# Generated by Django 5.0.7 on 2024-07-17 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inflows', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inflow',
            old_name='quantiy',
            new_name='quantity',
        ),
    ]
